Web_11/Areas/Admin/Pages/Role/AddUserRole.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Web_11.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Web_11.Areas.Admin.Pages.Role
{
    [Authorize(Roles = "Admin")]
    public class AddUserRole : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;


        public AddUserRole(RoleManager<IdentityRole> roleManager,
                            UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public class InputModel
        {
            [Required]
            public string ID { set; get; }
            public string Name { set; get; }

            public string[] RoleNames { set; get; }

        }

        [BindProperty]
        public InputModel Input { set; get; }

        [BindProperty]
        public bool isConfirmed { set; get; }

        [TempData] // Sử dụng Session
        public string StatusMessage { get; set; }

        public IActionResult OnGet() => NotFound("Không thấy");

        public List<string> AllRoles { set; get; } = new List<string>();

        public async Task<IActionResult> OnPost()
        {


            var user = await _userManager.FindByIdAsync(Input.ID);
            if (user == null)
            {
                return NotFound("Không thấy role cần xóa");
            }

            var roles = await _userManager.GetRolesAsync(user);
            var allroles = await _roleManager.Roles.ToListAsync();

            allroles.ForEach((r) => {
                AllRoles.Add(r.Name);
            });

            if (!isConfirmed)
            {
                Input.RoleNames = roles.ToArray();
                isConfirmed = true;
                StatusMessage = "";
                ModelState.Clear();
            }
            else
            {
                // Update add and remove
                StatusMessage = "Vừa cập nhật";
                if (Input.RoleNames == null) Input.RoleNames = new string[] { };
                foreach (var rolename in Input.RoleNames)
                {
                    if (roles.Contains(rolename)) continue;
                    await _userManager.AddToRoleAsync(user, rolename);
                }
                foreach (var rolename in roles)
                {
                    if (Input.RoleNames.Contains(rolename)) continue;
                    await _userManager.RemoveFromRoleAsync(user, rolename);
                }

            }

            Input.Name = user.UserName;
            return Page();
        }
    }
}

Web_11/Areas/Admin/Pages/Role/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_11.Areas.Admin.Pages.Role
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public DeleteModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public class InputModel
        {
            [Required]
            public string ID { set; get; }
            public string Name { set; get; }

        }

        [BindProperty]
        public InputModel Input { set; get; }

        [BindProperty]
        public bool isConfirmed { set; get; }

        [TempData] // Sử dụng Session
        public string StatusMessage { get; set; }

        public IActionResult OnGet() => NotFound("Không thấy");

        public async Task<IActionResult> OnPost()
        {

            if (!ModelState.IsValid)
            {
                return NotFound("Không xóa được");
            }

            var role = await _roleManager.FindByIdAsync(Input.ID);
            if (role == null)
            {
                return NotFound("Không thấy role cần xóa");
            }

            ModelState.Clear();

            if (isConfirmed)
            {
                //Xóa
                await _roleManager.DeleteAsync(role);
                StatusMessage = "Đã xóa " + role.Name;

                return RedirectToPage("Index");
            }
            else
            {
                Input.Name = role.Name;
                isConfirmed = true;

            }

            return Page();
        }
    }
}

Web_11/Areas/Admin/Pages/Role/add.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web_11.Models.data;

namespace Web_11.Areas.Admin.Pages.Role
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public AddModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [TempData] // Sử dụng Session
        public string StatusMessage { get; set; }

        public class InputModel
        {
            public string ID { set; get; }

            [Required(ErrorMessage = "Phải nhập tên role")]
            [Display(Name = "Tên của Role")]
            [StringLength(100, ErrorMessage = "{0} dài {2} đến {1} ký tự.", MinimumLength = 3)]
            public string Name { set; get; }

        }

        [BindProperty]
        public InputModel Input { set; get; }

        [BindProperty]
        public bool IsUpdate { set; get; }

        // Không cho truy cập trang mặc định mà không có handler
        public IActionResult OnGet() => NotFound("Không thấy");
        public IActionResult OnPost() => NotFound("Không thấy");


        public IActionResult OnPostStartNewRole()
        {
            StatusMessage = "Hãy nhập thông tin để tạo role mới";
            IsUpdate = false;
            ModelState.Clear();
            return Page();
        }

        // Truy vấn lấy thông tin Role cần cập nhật
        public async Task<IActionResult> OnPostStartUpdate()
        {
            StatusMessage = null;
            IsUpdate = true;
            if (Input.ID == null)
            {
                StatusMessage = "Error: Không có thông tin về Role";
                return Page();
            }
            var result = await _roleManager.FindByIdAsync(Input.ID);
            if (result != null)
            {
                Input.Name = result.Name;
                ViewData["Title"] = "Cập nhật role : " + Input.Name;
                ModelState.Clear();
            }
            else
            {
                StatusMessage = "Error: Không có thông tin về Role ID = " + Input.ID;
            }

            return Page();
        }

        // Cập nhật hoặc thêm mới tùy thuộc vào IsUpdate
        public async Task<IActionResult> OnPostAddOrUpdate()
        {

            if (!ModelState.IsValid)
            {
                StatusMessage = null;
                return Page();
            }

            if (IsUpdate)
            {
                // CẬP NHẬT
                if (Input.ID == null)
                {
                    ModelState.Clear();
                    StatusMessage = "Error: Không có thông tin về role";
                    return Page();
                }
                var result = await _roleManager.FindByIdAsync(Input.ID);
                if (result != null)
                {
                    result.Name = Input.Name;
                    // Cập nhật tên Role
                    var roleUpdateRs = await _roleManager.UpdateAsync(result);
                    if (roleUpdateRs.Succeeded)
                    {
                        StatusMessage = "Đã cập nhật role thành công";
                    }
                    else
                    {
                        StatusMessage = "Error: ";
                        foreach (var er in roleUpdateRs.Errors)
                        {
                            StatusMessage += er.Description;
                        }
                    }
                }
                else
                {
                    StatusMessage = "Error: Không tìm thấy Role cập nhật";
                }

            }
            else
            {
                // TẠO MỚI
                var newRole = new IdentityRole(Input.Name);
                // Thực hiện tạo Role mới
                var rsNewRole = await _roleManager.CreateAsync(newRole);
                if (rsNewRole.Succeeded)
                {
                    StatusMessage = $"Đã tạo role mới thành công: {newRole.Name}";
                    return RedirectToPage("./Index");
                }
                else
                {
                    StatusMessage = "Error: ";
                    foreach (var er in rsNewRole.Errors)
                    {
                        StatusMessage += er.Description;
                    }
                }
            }

            return Page();

        }
    }
}

Web_11/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Web_11.Models;
using Web_11.Models.data;

namespace Web_11.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly ILogger<TicketsController> _logger;
        public List<Doibong> doibongs { get; set; }
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[] ListVeVsLogo { get; set; }
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian) VeDuocChon { get; set; }
        private readonly FootballNewsContext _context;

        public TicketsController(ILogger<TicketsController> logger, FootballNewsContext context)
        {
            _context = context;
            _logger = logger;
        }
        [AllowAnonymous]
        // GET: Tickets
        public IActionResult Index()
        {
            TicketsViewsModel ticketsViewsModel = new TicketsViewsModel();
            ticketsViewsModel.hinhanhQcs = _context.HinhanhQc.ToList();
            ticketsViewsModel.tickets = _context.Ticket.ToList();
            ticketsViewsModel.trandaus = _context.Trandau.ToList();
            ticketsViewsModel.doibongs = _context.Doibong.ToList();
            ticketsViewsModel.ListVeVsLogo = GetListVe();
            return View(ticketsViewsModel);
        }
        // GET: Tickets/Details/5
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[] GetListVe()
        {
            List<Ticket> tempTicket = _context.Ticket.ToList();
            
            int temp = 0;
            ListVeVsLogo = new (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[100];
            foreach (var item in tempTicket)
            {
                ListVeVsLogo[temp] = (item.IdVe, GetLogoSrc(item.DoiNha), GetLogoSrc(item.DoiKhach), item.ThoiGianBatDau);
                temp++;
            }
            return ListVeVsLogo;
        }
        public string GetLogoSrc(string id)
        {
            string temp = "";
            foreach (var item in _context.Doibong)
            {
                if (item.IdDoiBong == id)
                {
                    temp = item.SourceLogo;
                }

            }
            return temp;
        }
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian) GetTicket(string id, (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[] listve)
        {
            foreach (var item in listve)
            {
                if (item.IDve==id)
                {
                     return item;
                }
            }
            return ("", "", "", null);
        }
       
            public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TicketsViewsModel ticketsViewsModel = new TicketsViewsModel();
            ticketsViewsModel.tickets = _context.Ticket.ToList();
            ticketsViewsModel.trandaus = _context.Trandau.ToList();
            ticketsViewsModel.doibongs = _context.Doibong.ToList();
            ticketsViewsModel.ListVeVsLogo = GetListVe();
            ticketsViewsModel.loaives = _context.Loaive.ToList();
            ticketsViewsModel.trandaus = _context.Trandau.ToList();
            ticketsViewsModel.doibongs = _context.Doibong.ToList();
            ticketsViewsModel.VeDuocChon = GetTicket(id,ListVeVsLogo);

            return View(ticketsViewsModel);
        }
        // Key lưu chuỗi json của Cart
        public const string CARTKEY = "cart";

        // Lấy cart từ Session (danh sách CartItem)
        List<CartItem> GetCartItems()
        {

            var session = HttpContext.Session;
            string jsoncart = session.GetString(CARTKEY);
            if (jsoncart != null)
            {
                return JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
            }
            return new List<CartItem>();
        }

        // Xóa cart khỏi session
        void ClearCart()
        {
            var session = HttpContext.Session;
            session.Remove(CARTKEY);
        }

        // Lưu Cart (Danh sách CartItem) vào session
        void SaveCartSession(List<CartItem> ls)
        {
            var session = HttpContext.Session;
            string jsoncart = JsonConvert.SerializeObject(ls);
            session.SetString(CARTKEY, jsoncart);
        }


        /// Thêm sản phẩm vào cart
        [Route("addcart/{productid}", Name = "addcart")]
        public IActionResult AddToCart([FromRoute] string productid)
        {

            var product = _context.Ticket
                .Where(p => p.IdVe == productid.ToString().Trim())
                .FirstOrDefault();
            if (product == null)
                return NotFound("Không có sản phẩm");

            // Xử lý đưa vào Cart ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.IdVe == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.quantity++;
            }
            else
            {
                //  Thêm mới
                cart.Add(new CartItem() { quantity = 1, product = product });
            }

            // Lưu cart vào Session
            SaveCartSession(cart);
            // Chuyển đến trang hiện thị Cart
            return RedirectToAction(nameof(Cart));
        }
        /// xóa item trong cart
        [Route("/removecart/{productid}", Name = "removecart")]
        public IActionResult RemoveCart([FromRoute] string productid)
        {
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.IdVe == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cart.Remove(cartitem);
            }

            SaveCartSession(cart);
            return RedirectToAction(nameof(Cart));
        }
        /// Cập nhật
        [Route("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart([FromForm] string productid, [FromForm] int quantity)
        {
            // Cập nhật Cart thay đổi số lượng quantity ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.IdVe == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.quantity = quantity;
            }
            SaveCartSession(cart);
            // Trả về mã thành công (không có nội dung gì - chỉ để Ajax gọi)
            return Ok();
        }
        // Hiện thị giỏ hàng
        [Route("/cart", Name = "cart")]
        public IActionResult Cart()
        {
            TicketsViewsModel ticketsViewsModel = new TicketsViewsModel();
            ticketsViewsModel.hinhanhQcs = _context.HinhanhQc.ToList();
            ticketsViewsModel.tickets = _context.Ticket.ToList();
            ticketsViewsModel.trandaus = _context.Trandau.ToList();
            ticketsViewsModel.doibongs = _context.Doibong.ToList();
            ticketsViewsModel.loaives = _context.Loaive.ToList();
            ticketsViewsModel.cartItems = GetCartItems();
            return View(ticketsViewsModel);
        }

        [Route("/checkout")]
        public IActionResult CheckOut()
        {
            // Xử lý khi đặt hàng
            return View();
        }

    }
}

Web_11/Areas/Admin/Pages/Role/AddUserRole.cshtml
@page
@model Web_11.Areas.Admin.Pages.Role.AddUserRole
@{
    ViewData["Title"] = "Cập nhật role cho User";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Chọn các role gán cho <strong>@Model.Input.Name</strong></p>
        <form method="post">
            <partial name="_StatusMessage" model="@Model.StatusMessage" />
            <div class="form-group">
                @Html.LabelFor(x => x.Input.RoleNames)
                @Html.ListBoxFor(x => x.Input.RoleNames,
                    new SelectList(Model.AllRoles),
                    new { @class = "w-100", id = "selectrole" })
            </div>

            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="isConfirmed">
            <a class="btn btn-primary" asp-page="./User">Danh sách</a>
            <button type="submit" class="btn btn-danger">Cập nhật</button>
        </form>
    </div>
</div>

@section Scripts {
    <script src="~/lib/multiple-select/dist/multiple-select.min.js"></script>
    <link rel="stylesheet" href="~/lib/multiple-select/dist/multiple-select.min.css" />
    <script>
          $('#selectrole').multipleSelect({
                selectAll: false,
                keepOpen: false,
                isOpen: false
            });
    </script>


    <partial name="_ValidationScriptsPartial" />
}

Web_11/Areas/Admin/Pages/Role/Delete.cshtml
@page
@model Web_11.Areas.Admin.Pages.Role.DeleteModel
@{
    ViewData["Title"] = "Xóa role";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Bạn có chăc chắn xóa Role <strong>@Model.Input.Name</strong> </p>
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="isConfirmed">
            <a class="btn btn-primary" asp-page="./Index">Danh sách</a>
            <button type="submit" asp-page="./Delete" class="btn btn-danger">Xóa</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Web_11/Areas/Admin/Pages/Role/DeleteUser.cshtml
@page
@model Web_11.Areas.Admin.Pages.Role.DeleteUserModel
@{
    ViewData["Title"] = "Xóa role";
}

<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-6">
        <p>Bạn có chăc chắn xóa Role <strong>@Model.Input.Name</strong> </p>
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="isConfirmed">
            <a class="btn btn-primary" asp-page="./Index">Danh sách</a>
            <button type="submit" asp-page="./Delete" class="btn btn-danger">Xóa</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Web_11/Areas/Admin/Pages/Role/Index.cshtml
@page "/admin/role/"
@model Web_11.Areas.Admin.Pages.IndexModel
@{
}

<h1>Danh sách các role</h1>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<form method="POST" class="my-1 d-inline">
    <button class="btn btn-secondary" asp-page="./Add"
            asp-page-handler="StartNewRole">
        Thêm mới Role
    </button>
</form>
<a class="btn btn-secondary" asp-page="./User">Gán role cho người dùng</a>


<table class="table">
    <tr>
        <th>Role ID</th>
        <th>Tên</th>
        <th>Tác vụ</th>
    </tr>
    @foreach (var role in @Model.roles)
    {
        <tr>
            <td>@role.Id</td>
            <td>@role.Name</td>
            <td>
                <form method="POST" class="d-inline">
                    <button name="Input.ID" value="@role.Id" class="btn btn-success btn-sm"
                            asp-page="./Add" asp-page-handler="StartUpdate">
                        Cập nhật Role
                    </button>
                </form>



                <a name="rolename" class="btn btn-success btn-sm"
                   asp-route-roleid="@role.Id"
                   asp-area="Admin"
                   asp-page="/RoleClaims/Index">Claims</a>

                <form method="POST" class="d-inline">
                    <button name="Input.ID" value="@role.Id" class="btn btn-success btn-sm"
                            asp-page="./Delete">
                        Xóa Role
                    </button>
                </form>

            </td>
        </tr>
    }
</table>

Web_11/Areas/Admin/Pages/Role/_Layout.cshtml
@{
    Layout = "/Views/Shared/Admin/_Layout.cshtml";
}

@RenderBody()
@section TopBar {
    @await Html.PartialAsync("/Views/Shared/Admin/_TopBar.cshtml")
}

@section SideBar {
    <partial name="/Areas/Admin/Pages/Role/_SideBar.cshtml" />
}

@section Scripts {
    @RenderSection("Scripts", required: false)
}

Web_11/Areas/Admin/Pages/Role/_SideBar.cshtml
@using Microsoft.AspNetCore.Identity
@using Web_11.Models
@inject SignInManager<AppUser> SignInManager
@{
    var hasExternalLogins = (await SignInManager.GetExternalAuthenticationSchemesAsync()).Any();
    string activePage = System.IO.Path.GetFileNameWithoutExtension(ViewContext.ActionDescriptor.DisplayName);
    Func<string, string, string> ActiveClass = (string activePage, string page) =>
    {
        return (activePage == page) ? "active" : "";
    };
}
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center"
           asp-action="Index" asp-controller="Home" asp-area="">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">XuanThuLab</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Heading -->
        <div class="sidebar-heading mt-2">
            Quản lý tài khoản
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUserManage" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Tài khoản cá nhân</span>
            </a>
            <div id="collapseUserManage" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Chức năng</h6>
                    <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/Index">Profile</a>
                    <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/Email">Email</a>
                    <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/ChangePassword">Password</a>
                    @if (hasExternalLogins)
                    {
                        <a class="collapse-item" asp-page="/Account/Manage/ExternalLogins">External logins</a>
                    }
                    <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/TwoFactorAuthentication">Two-factor authentication</a>
                    <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/PersonalData">Personal data</a>
                </div>
            </div>
        </li>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePhanquyen" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-user-cog"></i>
                <span>Phân quyền</span>
            </a>
            <div id="collapsePhanquyen" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item @ActiveClass(activePage, "Index")" asp-page="/Role/Index" asp-area="Admin">Vai trò - Role</a>
                    <a class="collapse-item @ActiveClass(activePage, "User")" asp-page="/Role/User" asp-area="Admin">Gán vai trò (phân quyền)</a>
                </div>
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Heading -->
        <div class="sidebar-heading mt-2">
            Posts
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePosts" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-newspaper"></i>
                <span>QL Bài viết</span>
            </a>
            <div id="collapsePosts" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" asp-controller="Tintucs" asp-area="Admin"><i class="fas fa-list"></i> Danh mục Tin Tức</a>
                    <a class="collapse-item" asp-controller="Tintucs" asp-area="Admin" asp-action="Index"><i class="fas fa-list"></i> Danh sách bài viết</a>
                    <a class="collapse-item" asp-controller="Tintucs" asp-area="Admin" asp-action="Create"><i class="fas fa-plus-circle"></i> Thêm bài viết</a>

                </div>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePosts" aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-newspaper"></i>
                <span>QL Bán vé</span>
            </a>
            <div id="collapsePosts" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" asp-controller="Tickets" asp-area="Admin"><i class="fas fa-list"></i> Danh mục Vé </a>
                    <a class="collapse-item" asp-controller="Tickets" asp-area="Admin" asp-action="Index"><i class="fas fa-list"></i> Danh sách Vé Đang bán</a>
                    <a class="collapse-item" asp-controller="Tickets" asp-area="Admin" asp-action="Create"><i class="fas fa-plus-circle"></i> Thêm Vé mới</a>
                </div>
            </div>
        </li>



        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
    </ul>
<!-- End of Sidebar -->

Web_11/Areas/Admin/Pages/Role/add.cshtml
@page "/admin/role/updaterole/{handler?}/"
@model Web_11.Areas.Admin.Pages.Role.AddModel
@{
    var btnText = Model.IsUpdate ? "Cập nhật" : "Tạo mới";
}


<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" model="@Model.StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Input.ID">
            <input type="hidden" asp-for="IsUpdate">
            <div class="form-group">
                <label asp-for="Input.Name"></label>
                <input asp-for="Input.Name" class="form-control">
                <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>

            <button id="add-or-edit-role" type="submit"
                    asp-page-handler="AddOrUpdate" class="btn btn-primary">
                @btnText
                </button>

                <a class="btn btn-primary" asp-page="./Index">Danh sách</a>
            </form>
        </div>
    </div>

    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }